### ISSUE TITLE
Add tag to target

### ISSUE THREAD

**Issue by fieldhof** [bpetri/nativeLoad#13]
When the deployment admin registers itself to ACE, it should give itself some tags to get the correct bundles (cpu_arch=armeabi, role=producer)

**Comment by bpetri** [comment]
For having the Ace AutoTargetOperator working, you need to add the ACE Client automation and afterwards perform a "cw" command on the shell. This  will trigger the creation of the StatefulTargetRepository. and the RepositoryAdmin, which in turn creates the needed targetRepository.

The only thing I don't understand is that I get a  `IllegalStateException: Another user is logged in` from the RepositoryAdminImpl. Setting a breakpoint there shows that the login is executed twice. First successfully and afterwards it fails.

**Comment by fieldhof** [comment]
I tried this and I get the same exception, but I think the bigger problem is that the AuditLogProcessTask is never executed, so the new targets don't get registered and approved

**Comment by bpetri** [comment]
You need to start it programmatically - this can be done by either registering to the processauditlog task and than start it (see the ClientAutomationTest.java:doAutoTargetReg()) or maybe try whether just starting it directly in the AutoTargetOperator does the same job.

**Comment by fieldhof** [comment]
When the AutoTargetOperator is started, it logs in to the RepositoryAdmin. But the AutoTargetOperator is only started if you try to get workspace (logging in via WebUI, getting a workspace through the REST API or via the 'cw' command in the GoGo shell). So you try to log in in some kind of way and the AutoTargetOperator is trying to log in. I tried to remove the login part at the AutoTargetOperator, but that didn't help. 

I tried to register to the service which didn't work for me. The last thing I tried was just executing the AuditLogProcessTask, but that only executed it once (duh). I set a breakpoint at AuditLogProcessTask:process() and saw that it didn't get through the whole method.  It didn't register or approve any targets. I think the code of the AutoTargetOperator is outdated but I may be wrong

**Comment by bpetri** [comment]
Dann, I actually also think the the AutoTargetOperator is outdated. But maybe we can easily fix it? Or re-use some of the code to create our own AutoTargetOperator?!

**Comment by fieldhof** [comment]
The illegalStateException is only thrown the first time you get a workspace, the second time it works.

I got help from Jan Willem through the mailing list, finally. We only have to add the org.apache.ace.client.automation bundle. We only forgot to add one line to the org.apache.ace.scheduler.cfg found in run-server-allinone/conf. The line was: org.apache.ace.client.processauditlog = 1000 where '1000'  is in ms and can be changed to whatever you want. We can now change the org.apache.ace.client.automation.cfg to filter some targets that have to be autoregistered and autoapproved. By default every target is autoregistered and autoapproved

**Comment by fieldhof** [comment]
We still have an issue where we can't get the distribution2target working correctly. We can't have a filter with 2 tags on an endpoint.

**Comment by fieldhof** [comment]
Fixed it by replacing "leftEndpoint" and "rightEndpoint" with "left" and "right" respectively
