### ISSUE TITLE
Stop framework when bundles active

### ISSUE THREAD

**Issue by fieldhof** [bpetri/nativeLoad#3]
If certain bundles are active and the framework is stopped, the application crashes. This is probably due to race conditions

**Comment by marcojansen** [comment]
Solved by using newest celix. However, destroy_properties doesn't work anymore. (jni_part.c executing destroy_properties after framework_destroy)

**Comment by bpetri** [comment]
This is usually caused by an slightly incorrect properties file. So, when you have e.g. doubled entries or values which does not have a proper KEY=VALUE format.

**Comment by bpetri** [comment]
I just had a another look at the code: in the current stage of development, the properties_destroy is done when executing the framework_destroy. Hence, a dedicated properties_destroy is not necessary anymore.

**Comment by marcojansen** [comment]
We removed the properties_destroy() function in the jnipart, which is the solution because the properties get destroyed in the framework_destroy.
