### ISSUE TITLE
Create Apache branch

### ISSUE THREAD

**Issue by bpetri** [bpetri/nativeLoad#30]
The original idea was to create an app which can be used to demonstrate how celix can be used from embedded devices like android. 

To be able to do so, we need to check whether there are licenses used which are not compatible with the Apache License and also change the inaetics-naming to an apache-naming.

**Comment by marcojansen** [comment]
I've found that all dependencies which we use are using the apache license except one.
This is the expandablelayout library which uses the MIT license: https://github.com/traex/ExpandableLayout/blob/master/LICENSE.txt 
This one uses the MIT license which is compatible with the apache license
http://apache.org/legal/resolved.html
