### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by fieldhof** [bpetri/nativeLoad#32]
Get the wiring up and running on the phones, so we can integrate the phones in the kubernetes-demo-cluster

**Comment by fieldhof** [comment]
Seems to work 'out-of-the-box' but there are some crashes. I had it working for at least 2 minutes with a Producer, Queue and Processor. It also failed sometimes at startup. I send the backtraces from logcat to Björn.

**Comment by marcojansen** [comment]
Works but there are still a lot errors, not very stable at all.
