### ISSUE TITLE
discovery endpoint poller

### ISSUE THREAD

**Issue by marcojansen** [bpetri/nativeLoad#6]
After stopping celix on a device the other phones are still trying to connect to the ip from it : unable to read endpoints message every +-5 seconds. Fix this issue

**Comment by marcojansen** [comment]
Seems that the config sometimes uses a wrong ip adress which might mess up the viewer and endpoint poller.

**Comment by bpetri** [comment]
Be aware that the discovery poller is updated lazy, i.e. an already removed server might still be polled which could lead to a temporarily blocked system (is this what you mean mess up?). Also see https://issues.apache.org/jira/browse/CELIX-273.

**Comment by marcojansen** [comment]
Fixed, The lazy polling still exists but this doesn't really cause any problems. When registering with a wrong RSA_IP the polling kept going until the device was disconnected. This has been fixed with the new config which keeps track of the current ip.
